// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReadConfig() {
  return window['go']['main']['DbConfig']['ReadConfig']();
}

export function UpdateConfig(arg1, arg2) {
  return window['go']['main']['DbConfig']['UpdateConfig'](arg1, arg2);
}
